Parametrize codedeploy max reversions
skyscrapers/puppet-codedeploy pull request #4
Opened 2018-07-03 10:24 UTC by minniux

To allow changing max_revisions to save disk space

Related issue: https://github.com/skyscrapers/puppet/issues/4363

2018-07-03 10:43 UTC, Komorebi-E approved these changes

2018-07-03 10:48 UTC, reyntjensw approved these changes

2018-07-03 10:49 UTC, venturel requested changes
What's the reason behind this?

2018-07-03 10:52 UTC, venturel commented
FYI you can already set that as `codedeploy:: max_revisions`.

2018-07-11 10:31 UTC, minniux commented
reverted and instead fixed the params lookup, now `codedeploy::max_revisions` can be used. Already tested

2018-07-11 10:32 UTC, merged